---
- hosts: all
  become: true
  vars:
    username: usertest1
  tasks:
    - name: Uberdel
      user:
        name: "{{username}}"
        state: absent
    - name: Del homedir
      file:
        path: "/home/{{username}}"
        state: absent
